- controller: controllers.UserController.UserController
  routes:
    - route: /api/users
      methods: ["GET"]
      endpoint: get_user
    - route: /api/users/login
      methods: ["POST"]
      endpoint: login

- controller: controllers.LeadsController.LeadsController
  routes:
    - route: /api/leads
      methods: ["POST"]
      endpoint: create_lead
    - route: /api/leads
      methods: ["GET"]
      endpoint: get_leads
    - route: /api/leads/<id>
      methods: ["GET"]
      endpoint: get_lead_by_id
    - route: /api/leads/dash-home
      methods: ["GET"]
      endpoint: get_dash_home
    - route: /api/leads/<id>
      methods: ["PUT"]
      endpoint: alter_lead

- controller: controllers.LandingPagesController.LandingPagesController
  routes:
    - route: /api/landing-pages
      methods: ["GET"]
      endpoint: get_all_lps
    - route: /api/landing-pages
      methods: ["POST"]
      endpoint: create_or_edit
    - route: /api/landing-pages/<id>
      methods: ["GET"]
      endpoint: get_by_id
