- controller: controllers.UserController.UserController
  routes:
    - route: /api/users
      methods: ["GET"]
      endpoint: get_user
    - route: /api/users/login
      methods: ["POST"]
      endpoint: login

- controller: controllers.EventsController.EventsController
  routes:
    - route: /api/events
      methods: ["GET"]
      endpoint: list_event
    - route: /api/events/delete/<id_event>
      methods: ["DELETE"]
      endpoint: delete_event

- controller: controllers.EmailController.EmailController
  routes:
    - route: /api/email
      methods: ["GET"]
      endpoint: list_all
    - route: /api/email/<id>/<email_data>
      methods: ["GET"]
      endpoint: get_email
    - route: /api/email
      methods: ["POST"]
      endpoint: create
    - route: /api/email/<id>
      methods: ["PUT"]
      endpoint: update_by_id
    - route: /api/email/<id>
      methods: ["DELETE"]
      endpoint: delete_email
    - route: /api/email/send
      methods: ["POST"]
      endpoint: send_email
    - route: /api/email/list-all
      methods: ["GET"]
      endpoint: list_all_variables

- controller: controllers.SystemController.SystemController
  routes:
    - route: /api/system/form-types
      methods: ["GET"]
      endpoint: list_form_types

    - route: /api/system/form-types-private
      methods: ["GET"]
      endpoint: list_form_types_private

- controller: controllers.LeadScoringController.LeadScoringController
  routes:
    - route: /api/lead-scoring
      methods: ["GET"]
      endpoint: list_all_perfil
    - route: /api/lead-scoring
      methods: ["POST"]
      endpoint: create_perfil
    - route: /api/lead-scoring
      methods: ["PUT"]
      endpoint: update_perfil
    - route: /api/lead-scoring/interesse
      methods: ["GET"]
      endpoint: list_all_interesse
    - route: /api/lead-scoring/interesse
      methods: ["POST"]
      endpoint: create_interesse
    - route: /api/lead-scoring/interesse
      methods: ["PUT"]
      endpoint: update_interesse

- controller: controllers.SegmentsController.SegmentsController
  routes:
    - route: /api/segments/<id_event>
      methods: ["POST"]
      endpoint: run_segments
    - route: /api/segments
      methods: ["GET"]
      endpoint: get_segments
    - route: /api/segments/rules
      methods: ["GET"]
      endpoint: get_rules

    - route: /api/segments/test
      methods: ["POST"]
      endpoint: test_run_segments

    - route: /api/segments/save
      methods: ["POST"]
      endpoint: save_segment

    - route: /api/segments/<id_segment>
      methods: ["GET"]
      endpoint: get_segment

    - route: /api/segments/create
      methods: ["post"]
      endpoint: create_new_segment

- controller: controllers.LeadsController.LeadsController
  routes:
    - route: /api/leads
      methods: ["POST"]
      endpoint: create_lead
    - route: /api/leads
      methods: ["GET"]
      endpoint: get_leads
    - route: /api/leads/<id>
      methods: ["GET"]
      endpoint: get_lead_by_id
    - route: /api/leads/dash-home
      methods: ["GET"]
      endpoint: get_dash_home
    - route: /api/leads/<id>
      methods: ["PUT"]
      endpoint: alter_lead

- controller: controllers.LandingPagesController.LandingPagesController
  routes:
    - route: /api/landing-pages
      methods: ["GET"]
      endpoint: get_all_lps
    - route: /api/landing-pages
      methods: ["POST"]
      endpoint: create_or_edit
    - route: /api/landing-pages/<id>
      methods: ["GET"]
      endpoint: get_by_id
